BookStore.WebApp/Areas/Admin/Controllers/CompanyController.cs
using BookStore.DataAccess.Repositories.IRepository;
using BookStore.Models;
using BookStore.Utilities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BookStore.WebApp.Areas.Admin.Controllers
{
	[Area("Admin")]
	[Authorize(Roles = StaticDetails.RoleAdmin)] // this attribute specifies that only users in the Admin role can access the CategoryController class.
	public class CompanyController : Controller
	{
		private readonly IUnitOfWork _unitOfWork;
		private readonly IWebHostEnvironment _hostEnvironment; // The IWebHostEnvironment interface is used to get the root path of the web application.
		public CompanyController(IUnitOfWork unitOfWork, IWebHostEnvironment hostEnvironment)
		{
			_unitOfWork = unitOfWork;
			_hostEnvironment = hostEnvironment; // We need to inject the IWebHostEnvironment interface into the CompanyController class.
		}

		public IActionResult Index()
		{
			IEnumerable<Company> objCompanyList = _unitOfWork.Company.GetAll();
			return View(objCompanyList);
		}

		// Combine the Create and Edit actions into one action called Upsert.
		// The Upsert action will be used for both creating and updating a product.
		// GET
		public IActionResult Upsert(int? id)
		{
			if (id == null || id == 0)
			{
				// this is for create
				return View(new Company());
			}
			// this is for edit
			Company companyObj = _unitOfWork.Company.Get(i => i.Id == id);
			if (companyObj == null)
			{
				return NotFound();
			}
			return View(companyObj);
		}
		// POST
		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Upsert(Company companyObj)
		{
			if (ModelState.IsValid)
			{
				if (companyObj.Id == 0)
				{
					_unitOfWork.Company.Insert(companyObj);
					TempData["success"] = "Company created successfully";
				}
				else
				{
					_unitOfWork.Company.Update(companyObj);
					TempData["success"] = "Company updated successfully";
				}
				_unitOfWork.Save();
				return RedirectToAction(nameof(Index));
			}
			return View(companyObj);
		}

		//// GET
		//public IActionResult Create()
		//{
		//	IEnumerable<SelectListItem> objCategoryList = _unitOfWork.Category.GetAll().Select(i => new SelectListItem
		//	{
		//		Text = i.Name,
		//		Value = i.Id.ToString()
		//	});
		//	// The SelectList class is used to create a list of items that are used to populate the drop-down list.
		//	// The SelectList class has two properties: Text and Value. The Text property is the text of the item,
		//	// and the Value property is the value that is submitted to the server when the item is selected.
		//	ProductVM productVM = new ProductVM()
		//	{
		//		Product = new Product(),
		//		CategoryList = objCategoryList
		//	};
		//	return View(productVM);		// The Create view will be strongly typed to the ProductVM class.
		//								// Therefore, now we can access the Product and CategoryList properties of the ProductVM class in the Create view.
		//								// No need lengthy code in the Create view anymore. This also enhances the security of the application.
		//}
		//// POST
		//[HttpPost]
		//[ValidateAntiForgeryToken]
		//public IActionResult Create(ProductVM productVM)
		//{
		//	if (ModelState.IsValid)
		//	{
		//		_unitOfWork.Product.Insert(productVM.Product);
		//		_unitOfWork.Save();
		//		TempData["success"] = "Product created successfully";
		//		return RedirectToAction(nameof(Index));
		//	}
		//	else
		//	{
		//		productVM.CategoryList = _unitOfWork.Category.GetAll().Select(i => new SelectListItem
		//		{
		//			Text = i.Name,
		//			Value = i.Id.ToString()
		//		});
		//		return View(productVM); // We need populate the CategoryList property of the ProductVM class again incase the form is not valid.
		//								// Otherwise, the drop-down list will be empty when the Create view is rendered.
		//	}
		//}

		//// GET
		//public IActionResult Edit(int? id)
		//{
		//	if (id == null || id == 0)
		//	{
		//		return NotFound();
		//	}

		//	var obj = _unitOfWork.Product.Get(i => i.Id == id);
		//	if (obj == null)
		//	{
		//		return NotFound();
		//	}

		//	return View(obj);
		//}
		//// POST
		//[HttpPost]
		//[ValidateAntiForgeryToken]
		//public IActionResult Edit(Product obj)
		//{
		//	if (ModelState.IsValid)
		//	{
		//		_unitOfWork.Product.Update(obj);
		//		_unitOfWork.Save();
		//		TempData["success"] = "Product updated successfully";
		//		return RedirectToAction(nameof(Index));
		//	}
		//	return View(obj);
		//}

		// GET
		//public IActionResult Delete(int? id)
		//{
		//	if (id == null || id == 0)
		//	{
		//		return NotFound();
		//	}

		//	var obj = _unitOfWork.Product.Get(i => i.Id == id);
		//	if (obj == null)
		//	{
		//		return NotFound();
		//	}

		//	return View(obj);
		//}
		//// POST
		//[HttpPost]
		//[ValidateAntiForgeryToken]
		//public IActionResult DeletePost(int? id)
		//{
		//	if (id == null || id == 0)
		//	{
		//		return NotFound();
		//	}

		//	var obj = _unitOfWork.Product.Get(i => i.Id == id);
		//	if (obj == null)
		//	{
		//		return NotFound();
		//	}
		//	_unitOfWork.Product.Delete(obj);
		//	_unitOfWork.Save();
		//	TempData["success"] = "Product deleted successfully";
		//	return RedirectToAction(nameof(Index));
		//}

		#region API CALLS

		[HttpGet]
		public IActionResult GetAll()
		{
			var allObj = _unitOfWork.Company.GetAll();
			return Json(new { data = allObj });
		}

		[HttpDelete]
		public IActionResult Delete(int? id)
		{
			var objFromDb = _unitOfWork.Company.Get(i => i.Id == id);
			if (objFromDb == null)
			{
				return Json(new { success = false, message = "Error while deleting" });
			}

			_unitOfWork.Company.Delete(objFromDb);
			_unitOfWork.Save();
			TempData["success"] = "Company deleted successfully";
			return Json(new { success = true, message = "Company deleted successfully" });
		}

		#endregion

	}
}

BookStore.WebApp/Areas/Admin/Controllers/OrderController.cs
using System.Security.Claims;
using BookStore.DataAccess.Repositories.IRepository;
using BookStore.Models;
using BookStore.Models.ViewModels;
using BookStore.Utilities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Stripe;
using Stripe.Checkout;

namespace BookStore.WebApp.Areas.Admin.Controllers;

[Area("Admin")]
[Authorize]
public class OrderController : Controller
{
    private readonly IUnitOfWork _unitOfWork;
    [BindProperty]
    public OrderVM OrderVm { get; set; } = new OrderVM();

    public OrderController(IUnitOfWork unitOfWork)
    {
        _unitOfWork = unitOfWork;
    }
    
    // GET
    public IActionResult Index()
    {
        return View();
    }
    
    // GET
    public IActionResult Details(int? id)
    {
        if (id is null or 0)
        {
            return NotFound();
        }
        OrderVm = new OrderVM
        {
            OrderHeader = _unitOfWork.OrderHeader.Get(o => o.Id == id, includeProperties: "ApplicationUser"),
            OrderDetails = _unitOfWork.OrderDetail.GetRange(o => o.OrderHeaderId == id, includeProperties: "Product")
        };
        return View(OrderVm);
    }
    
    // POST
    [HttpPost]
    [ValidateAntiForgeryToken]
    [Authorize(Roles = StaticDetails.RoleAdmin+","+StaticDetails.RoleEmployee)]
    public IActionResult UpdateOrderDetails()
    {
        var orderHeaderFromDb = _unitOfWork.OrderHeader.Get(o => o.Id == OrderVm.OrderHeader.Id); // this is the order header from the database
        orderHeaderFromDb.FullName = OrderVm.OrderHeader.FullName;
        orderHeaderFromDb.PhoneNumber = OrderVm.OrderHeader.PhoneNumber;
        orderHeaderFromDb.StreetAddress = OrderVm.OrderHeader.StreetAddress;
        orderHeaderFromDb.City = OrderVm.OrderHeader.City;
        orderHeaderFromDb.State = OrderVm.OrderHeader.State;
        orderHeaderFromDb.PostalCode = OrderVm.OrderHeader.PostalCode;

        if (!string.IsNullOrEmpty(OrderVm.OrderHeader.Carrier))
        {
            orderHeaderFromDb.Carrier = OrderVm.OrderHeader.Carrier;
        }
        if (!string.IsNullOrEmpty(OrderVm.OrderHeader.TrackingNumber))
        {
            orderHeaderFromDb.TrackingNumber = OrderVm.OrderHeader.TrackingNumber;
        }
        _unitOfWork.OrderHeader.Update(orderHeaderFromDb);
        _unitOfWork.Save();
        
        TempData["success"] = "Order details updated successfully";

        return RedirectToAction(nameof(Details), new {id = orderHeaderFromDb.Id});
    }
    
    [HttpPost]
    [ValidateAntiForgeryToken]
    [Authorize(Roles = StaticDetails.RoleAdmin + "," + StaticDetails.RoleEmployee)]
    public IActionResult StartProcessing()
    {
        _unitOfWork.OrderHeader.UpdateStatus(OrderVm.OrderHeader.Id, StaticDetails.OrderStatusInProcess);
        _unitOfWork.Save();
        
        TempData["success"] = "Order is in process";
        return RedirectToAction(nameof(Details), new {id = OrderVm.OrderHeader.Id});
    }
    
    [HttpPost]
    [ValidateAntiForgeryToken]
    [Authorize(Roles = StaticDetails.RoleAdmin + "," + StaticDetails.RoleEmployee)]
    public IActionResult ShipOrder()
    {
        var orderHeader = _unitOfWork.OrderHeader.Get(o => o.Id == OrderVm.OrderHeader.Id);
        orderHeader.TrackingNumber = OrderVm.OrderHeader.TrackingNumber;
        orderHeader.Carrier = OrderVm.OrderHeader.Carrier;
        orderHeader.ShippingDate = DateTime.Now;
        orderHeader.OrderStatus = StaticDetails.OrderStatusShipped;
        if (orderHeader.PaymentStatus == StaticDetails.PaymentStatusDelayedPayment)
        {
            orderHeader.PaymentDueDate = DateOnly.FromDateTime(DateTime.Now.AddDays(30));
        }
        
        _unitOfWork.OrderHeader.Update(orderHeader);
        _unitOfWork.Save();
        
        TempData["success"] = "Order is shipped";
        return RedirectToAction(nameof(Details), new {id = OrderVm.OrderHeader.Id});
    }
    
    [HttpPost]
    [ValidateAntiForgeryToken]
    [Authorize(Roles = StaticDetails.RoleAdmin + "," + StaticDetails.RoleEmployee)]
    public IActionResult CancelOrder()
    {
        var orderHeader = _unitOfWork.OrderHeader.Get(o => o.Id == OrderVm.OrderHeader.Id);
        
        if (orderHeader.PaymentStatus == StaticDetails.PaymentStatusApproved)
        {
            // Refund the money
            var options = new RefundCreateOptions // this is from Stripe
            {
                Reason = RefundReasons.RequestedByCustomer,
                PaymentIntent = orderHeader.PaymentIntentId
            };
            var service = new RefundService();
            Refund refund = service.Create(options);
            
            _unitOfWork.OrderHeader.UpdateStatus(OrderVm.OrderHeader.Id, StaticDetails.OrderStatusRefunded);
        }
        else
        {
            _unitOfWork.OrderHeader.UpdateStatus(OrderVm.OrderHeader.Id, StaticDetails.OrderStatusCancelled);
        }
        _unitOfWork.Save();
        
        TempData["success"] = "Order is cancelled successfully";
        return RedirectToAction(nameof(Details), new {id = OrderVm.OrderHeader.Id});
    }

	[HttpPost]
	[ValidateAntiForgeryToken]
	public IActionResult PayNow()
	{
        OrderVm.OrderHeader = _unitOfWork.OrderHeader.Get(o => o.Id == OrderVm.OrderHeader.Id, includeProperties: "ApplicationUser");
        OrderVm.OrderDetails = _unitOfWork.OrderDetail.GetRange(o => o.OrderHeaderId == OrderVm.OrderHeader.Id, includeProperties: "Product");

		var domain = $"{Request.Scheme}://{Request.Host.Value}/"; 
        // this will dynamically get the domain instead of hardcoding it
        // Request.Scheme will get the http or https and Request.Host.Value will get the domain name

		var options = new SessionCreateOptions
		{
			SuccessUrl = domain + $"Admin/Order/PaymentConfirmation?orderHeaderId={OrderVm.OrderHeader.Id}",
			CancelUrl = domain + "Admin/Oder/Details?orderHeaderId={OrderVm.OrderHeader.Id}",
			LineItems = new List<SessionLineItemOptions>(),
			Mode = "payment"
		};

        var shoppingCarts = OrderVm.OrderDetails.ToList();
		foreach (var item in shoppingCarts)
		{
			var sessionLineItem = new SessionLineItemOptions
			{
				PriceData = new SessionLineItemPriceDataOptions
				{
					UnitAmount = (long)(item.Price * 100),
					Currency = "usd",
					ProductData = new SessionLineItemPriceDataProductDataOptions
					{
						Name = item.Product.Title
					}
				},
				Quantity = item.Count
			};
			options.LineItems.Add(sessionLineItem);
		}
		var service = new SessionService();
		Session session = service.Create(options);

		_unitOfWork.OrderHeader.UpdateStripePaymentId(OrderVm.OrderHeader.Id, session.Id, session.PaymentIntentId);
		_unitOfWork.Save();
		Response.Headers.Append("Location", session.Url);
		return new StatusCodeResult(303);
	}
    
    // GET
    public IActionResult PaymentConfirmation(int orderHeaderId)
    {
        OrderHeader orderHeader = _unitOfWork.OrderHeader.Get(o => o.Id == orderHeaderId);
        if(orderHeader.PaymentStatus == StaticDetails.PaymentStatusDelayedPayment)
        {
            var service = new SessionService();
            Session session = service.Get(orderHeader.SessionId);
            if (session.PaymentStatus.ToLower() == "paid")
            {
                _unitOfWork.OrderHeader.UpdateStripePaymentId(orderHeaderId, session.Id, session.PaymentIntentId);
                _unitOfWork.OrderHeader.UpdateStatus(orderHeaderId, orderHeader.OrderStatus, StaticDetails.PaymentStatusApproved);
                _unitOfWork.Save();
            }
        }
        
        return View(orderHeaderId);
    }

	#region API CALLS

	[HttpGet]
    public IActionResult GetAll(string status)
    {
        IEnumerable<OrderHeader> orderHeaders;
        if (User.IsInRole(StaticDetails.RoleAdmin) || User.IsInRole(StaticDetails.RoleEmployee))
        {
            orderHeaders = _unitOfWork.OrderHeader.GetAll(includeProperties: "ApplicationUser").ToList();
        }
        else
        {
            var claimsIdentity = (ClaimsIdentity) User.Identity!;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier)!.Value;
            orderHeaders = _unitOfWork.OrderHeader.GetRange(o => o.ApplicationUserId == claim, includeProperties: "ApplicationUser").ToList();
        }

        orderHeaders = status switch
        {
            "pending" => orderHeaders.Where(o => o.PaymentStatus == StaticDetails.PaymentStatusDelayedPayment),
            "inprocess" => orderHeaders.Where(o => o.PaymentStatus == StaticDetails.OrderStatusInProcess),
            "completed" => orderHeaders.Where(o => o.PaymentStatus == StaticDetails.OrderStatusShipped),
            "approved" => orderHeaders.Where(o => o.PaymentStatus == StaticDetails.OrderStatusApproved),
            _ => orderHeaders
        };

        return Json(new {data = orderHeaders});
    }

    #endregion
    
}

BookStore.WebApp/Views/Shared/_Layout.cshtml
@using BookStore.Utilities
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8"/>
	<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
	<title>@ViewData["Title"] - WebApplicationTest</title>
	<link rel="icon" href="~/ameIcon.ico" type="image/x-icon"/>
	<link rel="stylesheet" href="~/css/bootstrapSolar.css"/>
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
	<link rel="stylesheet" href="~/WebApplicationTest.styles.css" asp-append-version="true"/>
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css">
	<link rel="stylesheet" href="//cdn.datatables.net/1.13.7/css/jquery.dataTables.min.css"/>
	<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css"/>
</head>
<body>
<header>
	<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark box-shadow" data-bs-theme="dark">
		<div class="container-fluid">
			<a class="navbar-brand" href="#">
				<i class="bi bi-book"></i>
			</a>
			<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarColor01">
				<ul class="navbar-nav me-auto">
					<li class="nav-item">
						<a class="nav-link" asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
						@*
							The asp-area, asp-controller, and asp-action are all part of ASP.NET Core’s built-in Tag Helpers.
							These Tag Helpers are used for generating links.
							For example, <a asp-controller="Home" asp-action="Index">Home</a> might be rendered as <a href="/Home/Index">Home</a>
							*@
					</li>
					<li class="nav-item">
						<a class="nav-link" asp-area="Admin" asp-controller="Order" asp-action="Index">Manage Order</a>
					</li>
					@if (User.IsInRole(StaticDetails.RoleAdmin))
					{
						<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Content Management</a>
							<div class="dropdown-menu">
								<a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a>
								<a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
								<div class="dropdown-divider"></div>
								<a class="dropdown-item" asp-area="Admin" asp-controller="Company" asp-action="Index">Company</a>
								<div class="dropdown-divider"></div>
								<a class="dropdown-item" asp-area="Identity" asp-page="/Account/Register">Register User</a> <!-- Create a Register User function in the Admin role -->
							</div>
						</li>
					}
					<li class="nav-item">
						<a class="nav-link" asp-area="Customer" asp-controller="Home" asp-action="Privacy">Privacy</a>
					</li>
				</ul>
				<partial name="_LoginPartial"></partial>
			</div>
		</div>
	</nav>

</header>
<div class="container">
	<main role="main" class="pb-3">
		@RenderBody()
	</main>
</div>

<footer class="footer text-muted bg-dark">
	<div class="text-center">
		WebApplicationTest - 2023 - Made by HNV <i class="bi bi-cloud-drizzle-fill"></i> - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
	</div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
@* <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script> *@
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="https://cdn.tiny.cloud/1/wy2b1ziplbxnbfrpxsro3h7cf811ojxheczubwqlwwb43nns/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
<script src="//cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js" asp-append-version="true"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BookStore.WebApp/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

	<script type="text/javascript">
		toastr.success('@TempData["success"]');
	</script>
}

@if (TempData["error"] != null)
{
	<div class="container p-3" style="position: fixed; bottom: 35px; right: 0; width: auto;">

		<div class="alert alert-dismissible alert-danger fade show" role="alert">
			<strong>Oh snap!</strong>
			<div asp-validation-summary="ModelOnly"></div>
			<button type="button" class="btn-close" data-bs-dismiss="alert"></button>
		</div>

	</div>
}

@if (TempData["error_cus"] != null)
{
	<div class="container p-3" style="position: fixed; bottom: 35px; right: 0; width: auto;">

		<div class="alert alert-dismissible alert-warning fade show" role="alert">
			<strong>Error</strong>
			<div class="container">@TempData["error_cus"]</div>
			<button type="button" class="btn-close" data-bs-dismiss="alert"></button>
		</div>

	</div>
}