BookStore.WebApp/Areas/Admin/Controllers/CompanyController.cs
using BookStore.DataAccess.Repositories.IRepository;
using BookStore.Models;
using BookStore.Utilities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BookStore.WebApp.Areas.Admin.Controllers
{
	[Area("Admin")]
	[Authorize(Roles = StaticDetails.RoleAdmin)] // this attribute specifies that only users in the Admin role can access the CategoryController class.
	public class CompanyController : Controller
	{
		private readonly IUnitOfWork _unitOfWork;
		private readonly IWebHostEnvironment _hostEnvironment; // The IWebHostEnvironment interface is used to get the root path of the web application.
		public CompanyController(IUnitOfWork unitOfWork, IWebHostEnvironment hostEnvironment)
		{
			_unitOfWork = unitOfWork;
			_hostEnvironment = hostEnvironment; // We need to inject the IWebHostEnvironment interface into the CompanyController class.
		}

		public IActionResult Index()
		{
			IEnumerable<Company> objCompanyList = _unitOfWork.Company.GetAll();
			return View(objCompanyList);
		}

		// Combine the Create and Edit actions into one action called Upsert.
		// The Upsert action will be used for both creating and updating a product.
		// GET
		public IActionResult Upsert(int? id)
		{
			if (id == null || id == 0)
			{
				// this is for create
				return View(new Company());
			}
			// this is for edit
			Company companyObj = _unitOfWork.Company.Get(i => i.Id == id);
			if (companyObj == null)
			{
				return NotFound();
			}
			return View(companyObj);
		}
		// POST
		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Upsert(Company companyObj)
		{
			if (ModelState.IsValid)
			{
				if (companyObj.Id == 0)
				{
					_unitOfWork.Company.Insert(companyObj);
					TempData["success"] = "Company created successfully";
				}
				else
				{
					_unitOfWork.Company.Update(companyObj);
					TempData["success"] = "Company updated successfully";
				}
				_unitOfWork.Save();
				return RedirectToAction(nameof(Index));
			}
			return View(companyObj);
		}

		//// GET
		//public IActionResult Create()
		//{
		//	IEnumerable<SelectListItem> objCategoryList = _unitOfWork.Category.GetAll().Select(i => new SelectListItem
		//	{
		//		Text = i.Name,
		//		Value = i.Id.ToString()
		//	});
		//	// The SelectList class is used to create a list of items that are used to populate the drop-down list.
		//	// The SelectList class has two properties: Text and Value. The Text property is the text of the item,
		//	// and the Value property is the value that is submitted to the server when the item is selected.
		//	ProductVM productVM = new ProductVM()
		//	{
		//		Product = new Product(),
		//		CategoryList = objCategoryList
		//	};
		//	return View(productVM);		// The Create view will be strongly typed to the ProductVM class.
		//								// Therefore, now we can access the Product and CategoryList properties of the ProductVM class in the Create view.
		//								// No need lengthy code in the Create view anymore. This also enhances the security of the application.
		//}
		//// POST
		//[HttpPost]
		//[ValidateAntiForgeryToken]
		//public IActionResult Create(ProductVM productVM)
		//{
		//	if (ModelState.IsValid)
		//	{
		//		_unitOfWork.Product.Insert(productVM.Product);
		//		_unitOfWork.Save();
		//		TempData["success"] = "Product created successfully";
		//		return RedirectToAction(nameof(Index));
		//	}
		//	else
		//	{
		//		productVM.CategoryList = _unitOfWork.Category.GetAll().Select(i => new SelectListItem
		//		{
		//			Text = i.Name,
		//			Value = i.Id.ToString()
		//		});
		//		return View(productVM); // We need populate the CategoryList property of the ProductVM class again incase the form is not valid.
		//								// Otherwise, the drop-down list will be empty when the Create view is rendered.
		//	}
		//}

		//// GET
		//public IActionResult Edit(int? id)
		//{
		//	if (id == null || id == 0)
		//	{
		//		return NotFound();
		//	}

		//	var obj = _unitOfWork.Product.Get(i => i.Id == id);
		//	if (obj == null)
		//	{
		//		return NotFound();
		//	}

		//	return View(obj);
		//}
		//// POST
		//[HttpPost]
		//[ValidateAntiForgeryToken]
		//public IActionResult Edit(Product obj)
		//{
		//	if (ModelState.IsValid)
		//	{
		//		_unitOfWork.Product.Update(obj);
		//		_unitOfWork.Save();
		//		TempData["success"] = "Product updated successfully";
		//		return RedirectToAction(nameof(Index));
		//	}
		//	return View(obj);
		//}

		// GET
		//public IActionResult Delete(int? id)
		//{
		//	if (id == null || id == 0)
		//	{
		//		return NotFound();
		//	}

		//	var obj = _unitOfWork.Product.Get(i => i.Id == id);
		//	if (obj == null)
		//	{
		//		return NotFound();
		//	}

		//	return View(obj);
		//}
		//// POST
		//[HttpPost]
		//[ValidateAntiForgeryToken]
		//public IActionResult DeletePost(int? id)
		//{
		//	if (id == null || id == 0)
		//	{
		//		return NotFound();
		//	}

		//	var obj = _unitOfWork.Product.Get(i => i.Id == id);
		//	if (obj == null)
		//	{
		//		return NotFound();
		//	}
		//	_unitOfWork.Product.Delete(obj);
		//	_unitOfWork.Save();
		//	TempData["success"] = "Product deleted successfully";
		//	return RedirectToAction(nameof(Index));
		//}

		#region API CALLS

		[HttpGet]
		public IActionResult GetAll()
		{
			var allObj = _unitOfWork.Company.GetAll();
			return Json(new { data = allObj });
		}

		[HttpDelete]
		public IActionResult Delete(int? id)
		{
			var objFromDb = _unitOfWork.Company.Get(i => i.Id == id);
			if (objFromDb == null)
			{
				return Json(new { success = false, message = "Error while deleting" });
			}

			_unitOfWork.Company.Delete(objFromDb);
			_unitOfWork.Save();
			TempData["success"] = "Company deleted successfully";
			return Json(new { success = true, message = "Company deleted successfully" });
		}

		#endregion

	}
}

BookStore.WebApp/Areas/Admin/Controllers/ProductController.cs
using BookStore.DataAccess.Repositories.IRepository;
using BookStore.Models;
using BookStore.Models.ViewModels;
using BookStore.Utilities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BookStore.WebApp.Areas.Admin.Controllers
{
	[Area("Admin")]
	[Authorize(Roles = StaticDetails.RoleAdmin)] // this attribute specifies that only users in the Admin role can access the CategoryController class.
	public class ProductController : Controller
	{
		private readonly IUnitOfWork _unitOfWork;
		private readonly IWebHostEnvironment _hostEnvironment; // The IWebHostEnvironment interface is used to get the root path of the web application.
		public ProductController(IUnitOfWork unitOfWork, IWebHostEnvironment hostEnvironment)
		{
			_unitOfWork = unitOfWork;
			_hostEnvironment = hostEnvironment; // We need to inject the IWebHostEnvironment interface into the ProductController class.
		}

		public IActionResult Index()
		{
			IEnumerable<Product> objProductList = _unitOfWork.Product.GetAll(includeProperties: "Category");
			return View(objProductList);
		}

		// Combine the Create and Edit actions into one action called Upsert.
		// The Upsert action will be used for both creating and updating a Company.
		// GET
		public IActionResult Upsert(int? id)
		{
			ProductVM productVM = new()
			{
				CategoryList = _unitOfWork.Category.GetAll().Select(u => new SelectListItem
				{
					Text = u.Name,
					Value = u.Id.ToString()
				}),
				Product = new Product()
			};
			if (id == null || id == 0)
			{
				// this is for create
				// set the image url to the default image
				productVM.Product.ImageUrl = @"\images\product\Default.png";
				return View(productVM);
			}
			// this is for edit
			productVM.Product = _unitOfWork.Product.Get(u => u.Id == id);
			return View(productVM);
		}
		// POST
		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Upsert(ProductVM productVM, IFormFile? file)
		{
			if (ModelState.IsValid)
			{
				string webRootPath = _hostEnvironment.WebRootPath; // The WebRootPath property of the IWebHostEnvironment interface returns the absolute path to the web root directory.
				if (file != null)
				{
					// if user uploads an image
					string upload = Path.Combine(webRootPath, @"images\product"); // this give us the path to the images/product folder
					string fileName = Guid.NewGuid().ToString(); // The Guid class is used to generate a unique string value.
					string extension = Path.GetExtension(file.FileName);

					if (!string.IsNullOrEmpty(productVM.Product.ImageUrl))
					{
						// this is an edit and we need to remove old image
						var imagePath = Path.Combine(webRootPath, productVM.Product.ImageUrl.TrimStart('\\')); // Use TrimStart('\\') to remove the leading backslash (\) from the ImageUrl property.
						if (System.IO.File.Exists(imagePath))
						{
							System.IO.File.Delete(imagePath);
						}
					}

					using (var fileStream = new FileStream(Path.Combine(upload, fileName + extension), FileMode.Create))
					{
						file.CopyTo(fileStream);
					}
					productVM.Product.ImageUrl = @"\images\product\" + fileName + extension;
				}
				if (productVM.Product.Id == 0)
				{
					_unitOfWork.Product.Insert(productVM.Product);
					TempData["success"] = "Product created successfully";
				}
				else
				{
					_unitOfWork.Product.Update(productVM.Product);
					TempData["success"] = "Product updated successfully"; }
				_unitOfWork.Save();
				return RedirectToAction(nameof(Index));
			}
			return View(productVM);
		}

		// Old code
		//// GET
		//public IActionResult Create()
		//{
		//	IEnumerable<SelectListItem> objCategoryList = _unitOfWork.Category.GetAll().Select(i => new SelectListItem
		//	{
		//		Text = i.Name,
		//		Value = i.Id.ToString()
		//	});
		//	// The SelectList class is used to create a list of items that are used to populate the drop-down list.
		//	// The SelectList class has two properties: Text and Value. The Text property is the text of the item,
		//	// and the Value property is the value that is submitted to the server when the item is selected.
		//	CompanyVM CompanyVM = new CompanyVM()
		//	{
		//		Company = new Company(),
		//		CategoryList = objCategoryList
		//	};
		//	return View(CompanyVM);		// The Create view will be strongly typed to the CompanyVM class.
		//								// Therefore, now we can access the Company and CategoryList properties of the CompanyVM class in the Create view.
		//								// No need lengthy code in the Create view anymore. This also enhances the security of the application.
		//}
		//// POST
		//[HttpPost]
		//[ValidateAntiForgeryToken]
		//public IActionResult Create(CompanyVM CompanyVM)
		//{
		//	if (ModelState.IsValid)
		//	{
		//		_unitOfWork.Company.Insert(CompanyVM.Company);
		//		_unitOfWork.Save();
		//		TempData["success"] = "Company created successfully";
		//		return RedirectToAction(nameof(Index));
		//	}
		//	else
		//	{
		//		CompanyVM.CategoryList = _unitOfWork.Category.GetAll().Select(i => new SelectListItem
		//		{
		//			Text = i.Name,
		//			Value = i.Id.ToString()
		//		});
		//		return View(CompanyVM); // We need populate the CategoryList property of the CompanyVM class again incase the form is not valid.
		//								// Otherwise, the drop-down list will be empty when the Create view is rendered.
		//	}
		//}

		//// GET
		//public IActionResult Edit(int? id)
		//{
		//	if (id == null || id == 0)
		//	{
		//		return NotFound();
		//	}

		//	var obj = _unitOfWork.Company.Get(i => i.Id == id);
		//	if (obj == null)
		//	{
		//		return NotFound();
		//	}

		//	return View(obj);
		//}
		//// POST
		//[HttpPost]
		//[ValidateAntiForgeryToken]
		//public IActionResult Edit(Company obj)
		//{
		//	if (ModelState.IsValid)
		//	{
		//		_unitOfWork.Company.Update(obj);
		//		_unitOfWork.Save();
		//		TempData["success"] = "Company updated successfully";
		//		return RedirectToAction(nameof(Index));
		//	}
		//	return View(obj);
		//}

		// GET
		//public IActionResult Delete(int? id)
		//{
		//	if (id == null || id == 0)
		//	{
		//		return NotFound();
		//	}

		//	var obj = _unitOfWork.Company.Get(i => i.Id == id);
		//	if (obj == null)
		//	{
		//		return NotFound();
		//	}

		//	return View(obj);
		//}
		//// POST
		//[HttpPost]
		//[ValidateAntiForgeryToken]
		//public IActionResult DeletePost(int? id)
		//{
		//	if (id == null || id == 0)
		//	{
		//		return NotFound();
		//	}

		//	var obj = _unitOfWork.Company.Get(i => i.Id == id);
		//	if (obj == null)
		//	{
		//		return NotFound();
		//	}
		//	_unitOfWork.Company.Delete(obj);
		//	_unitOfWork.Save();
		//	TempData["success"] = "Company deleted successfully";
		//	return RedirectToAction(nameof(Index));
		//}

		#region API CALLS

		[HttpGet]
		public IActionResult GetAll()
		{
			var allObj = _unitOfWork.Product.GetAll(includeProperties: "Category");
			return Json(new { data = allObj });
		}

		[HttpDelete]
		public IActionResult Delete(int? id)
		{
			var objFromDb = _unitOfWork.Product.Get(i => i.Id == id);
			if (objFromDb == null)
			{
				return Json(new { success = false, message = "Error while deleting" });
			}
			var imagePath = Path.Combine(_hostEnvironment.WebRootPath, objFromDb.ImageUrl.TrimStart('\\'));
			// check if the image is Default.png, if it is, we don't want to delete it
			if (System.IO.File.Exists(imagePath) && !imagePath.Contains("Default.png"))
			{
				System.IO.File.Delete(imagePath);
			}

			_unitOfWork.Product.Delete(objFromDb);
			_unitOfWork.Save();
			TempData["success"] = "Product deleted successfully";
			return Json(new { success = true, message = "Product deleted successfully" });
		}

		#endregion

	}
}

BookStore.WebApp/Areas/Admin/Views/Company/Index.cshtml
@model IEnumerable<BookStore.Models.Company>

<div class="container p-3">

	<figure class="text-center">
		<img src="~/images/CATcd9667b5.png" alt="Cat Image" width="300" />
		<figcaption>cat</figcaption>
	</figure>

	<div class="row mb-2">
		<div class="col-6">
			<h2 class="text-primary">Company list</h2>
		</div>
		<div class="col-6 text-end">
			<a asp-controller="Company" asp-action="Upsert" class="btn btn-outline-primary">
				<i class="bi bi-plus-circle"></i> &nbsp; New Company
			</a>
		</div>
	</div>

	<table class="table table-striped table-bordered" id="tblData" style="width: 100%">
		<thead>
			<tr class="table-primary">
				<th>Name</th>
				<th>Address</th>
				<th>City</th>
				<th>State</th>
				<th>Postal Code</th>
				<th>Phone</th>

				<th>
					<div class="text-center">
						<i class="bi bi-sliders"></i>
					</div>
				</th>
			</tr>
		</thead>
		@* <tbody>
		@foreach (var item in Model)
		{
		<tr>
		<td class="text-light" style="width:20%">@item.Title</td>
		<td class="text-light" style="width:15%">@item.ISBN</td>
		<td class="text-light" style="width:15%">@item.Category.Name</td>
		<td class="text-light" style="width:15%">@item.Author</td>
		<td class="text-light" style="width:80px">@item.ListPrice$</td>
		<td class="text-light" style="width:80px">@item.Price$</td>
		<td class="text-light" style="width:80px">@item.Price50$</td>
		<td class="text-light" style="width:80px">@item.Price100$</td>
		<td class="text-center" style="width:80px">
		<style>
		.btn-custom {
		padding: 0px 4px;
		}
		</style>

		<a asp-controller="Product" asp-action="Upsert" asp-route-id="@item.Id" class="btn btn-outline-primary btn-custom">
		<i class="bi bi-pencil-square"></i>
		</a>
		<a asp-controller="Product" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-outline-danger btn-custom">
		<i class="bi bi-trash"></i>
		</a>
		</td>
		</tr>
		}
		</tbody> *@
	</table>
</div>

<partial name="_Notification"></partial>

@section Scripts {
	<script src="~/js/company.js">
	</script>
}

BookStore.WebApp/Areas/Admin/Views/Company/Upsert.cshtml
@model BookStore.Models.Company

<div class="card text-white bg-dark shadow border-0 mt-3">
	<div class="card-header bg-secondary bg-gradient">
		<div class="row">
			<div>
				<h3 class="text-dark">@(Model.Id != 0 ? "Update" : "Create") Company</h3>
			</div>
		</div>
	</div>
	<div class="card-body p-3">
		<div class="container text-center">
			<figure>
				@if (Model.Id != 0)
				{
					<img src="~/images/catHuh!!!.png" alt="Cat Image" width="300" />
				}
				else
				{
					<img src="~/images/catChild.png" alt="Cat Image" width="300" />
				}
				<figcaption>cat</figcaption>
			</figure>
		</div>
		<form method="post">
			<input asp-for=Id type="hidden" />
			<div class="row justify-content-center text-center">
				<div class="col-9">
					<div class="form-floating mb-3 col-12">
						<input asp-for=Name type="text" class="form-control border-0 shadow" id="inputName" placeholder="Enter category name" />
						<label asp-for=Name class="form-label text-dark"></label>
						<span asp-validation-for=Name class="text-danger"></span>
					</div>
					<div class="form-floating mb-3 col-12">
						<input asp-for=Phone type="text" class="form-control border-0 shadow" id="inputISBN" placeholder="Enter ISBN" />
						<label asp-for=Phone class ="form-label text-dark"></label>
						<span asp-validation-for=Phone class="text-danger"></span>
					</div>
					<div class="form-floating mb-3 col-12">
						<input asp-for=StreetAddress type="text" class="form-control border-0 shadow" id="inputAuthor" placeholder="Enter author" />
						<label asp-for=StreetAddress class="form-label text-dark"></label>
						<span asp-validation-for=StreetAddress class="text-danger"></span>
					</div>
					<div class="form-floating mb-3 col-12">
						<input asp-for=City type="text" class="form-control border-0 shadow" id="inputListPrice" placeholder="Enter list price">
						<label asp-for=City class="form-label text-dark"></label>
						<span asp-validation-for=City class="text-danger"></span>
					</div>
					<div class="form-floating mb-3 col-12">
						<input asp-for=State type="text" class="form-control border-0 shadow" id="inputPrice" placeholder="Enter price" />
						<label asp-for=State class="form-label text-dark"></label>
						<span asp-validation-for=State class="text-danger"></span>
					</div>
					<div class="form-floating mb-3 col-12">
						<input asp-for=PostalCode type="number" class="form-control border-0 shadow" id="inputPrice50" placeholder="Enter price" />
						<label asp-for=PostalCode class="form-label text-dark"></label>
						<span asp-validation-for=PostalCode class="text-danger"></span>
					</div>

					<div class="row">
						<div class="col-6 col-md-3">
							@if (Model.Id != 0)
							{
								<button type="submit" class="btn btn-primary form-control">Update the company</button>
							}
							else
							{
								<button type="submit" class="btn btn-success form-control">Create new company</button>
							}
						</div>
						<div class="col-6 col-md-3">
							<a asp-controller="Company" asp-action="Index" class="btn btn-outline-secondary border form-control">Back to the list</a>
						</div>
					</div>
				</div>
			</div>
		</form>
	</div>
</div>


<partial name="_Notification"></partial>